version: '3.8'

services:
  postgres:
    image: public.ecr.aws/docker/library/postgres:15
    container_name: task-postgres
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-network

  backend:
    build: ./backend
    container_name: task-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - JWT_SECRET=your_super_secret_jwt_key_here_change_in_production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=taskmanager
      - DB_USER=postgres
      - DB_PASSWORD=password
    depends_on:
      - postgres
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - task-network

  frontend:
    build: ./frontend
    container_name: task-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - task-network

networks:
  task-network:
    driver: bridge

volumes:
  postgres_data:
